// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olbrasoft.OpenCode.Extensions.Data.EntityFrameworkCore;

#nullable disable

namespace OpenCode.Extensions.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(OpenCodeDbContext))]
    [Migration("20251203172739_AddUniqueRootMessagePerSessionConstraint")]
    partial class AddUniqueRootMessagePerSessionConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ModeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentMessageId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensInput")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensOutput")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ModeId");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Messages_SessionId_RootMessage")
                        .HasFilter("\"ParentMessageId\" IS NULL");

                    b.ToTable("Messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Messages_Content_NotEmpty", "length(\"Content\") > 0");
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.ModeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Modes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Build"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plan"
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ParticipantTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("ParticipantTypeId");

                    b.ToTable("Participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "user-jirka",
                            Label = "Jirka",
                            ParticipantTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "claude-haiku-4.5",
                            Label = "Claude Haiku 4.5",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Identifier = "claude-opus-4.1",
                            Label = "Claude Opus 4.1",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Identifier = "claude-opus-4.5",
                            Label = "Claude Opus 4.5",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Identifier = "claude-sonnet-4",
                            Label = "Claude Sonnet 4",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Identifier = "claude-sonnet-4.5",
                            Label = "Claude Sonnet 4.5",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Identifier = "gpt-4.1",
                            Label = "GPT-4.1",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Identifier = "gpt-5",
                            Label = "GPT-5",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Identifier = "gpt-5-mini",
                            Label = "GPT-5 mini",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Identifier = "gpt-5-codex",
                            Label = "GPT-5-Codex",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Identifier = "gpt-5.1",
                            Label = "GPT-5.1",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Identifier = "gpt-5.1-codex",
                            Label = "GPT-5.1-Codex",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Identifier = "gpt-5.1-codex-mini",
                            Label = "GPT-5.1-Codex-Mini",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Identifier = "raptor-mini",
                            Label = "Raptor mini",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Identifier = "gemini-2.5-pro",
                            Label = "Gemini 2.5 Pro",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Identifier = "gemini-3-pro",
                            Label = "Gemini 3 Pro",
                            ParticipantTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            Identifier = "grok-code-fast-1",
                            Label = "Grok Code Fast 1",
                            ParticipantTypeId = 2
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.ParticipantTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ParticipantTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AiModel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Script"
                        },
                        new
                        {
                            Id = 4,
                            Name = "System"
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Human input (keyboard, voice, or combination)",
                            Name = "HumanInput"
                        },
                        new
                        {
                            Id = 2,
                            Description = "System pipeline - voice processing orchestration",
                            Name = "VoiceAssistant"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Claude models via Anthropic API",
                            Name = "Anthropic"
                        },
                        new
                        {
                            Id = 4,
                            Description = "GPT models via OpenAI API",
                            Name = "OpenAI"
                        },
                        new
                        {
                            Id = 5,
                            Description = "GitHub Copilot (routes to various models)",
                            Name = "GitHubCopilot"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gemini models via Google AI",
                            Name = "Google"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Azure OpenAI Service",
                            Name = "AzureOpenAI"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Grok models via xAI",
                            Name = "xAI"
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Message", b =>
                {
                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.ModeEntity", "ModeEntity")
                        .WithMany("Messages")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Message", "ParentMessage")
                        .WithMany("ChildMessages")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", "Participant")
                        .WithMany("Messages")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", "Provider")
                        .WithMany("Messages")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeEntity");

                    b.Navigation("ParentMessage");

                    b.Navigation("Participant");

                    b.Navigation("Provider");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", b =>
                {
                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.ParticipantTypeEntity", "ParticipantType")
                        .WithMany("Participants")
                        .HasForeignKey("ParticipantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParticipantType");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Message", b =>
                {
                    b.Navigation("ChildMessages");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.ModeEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.ParticipantTypeEntity", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
