// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olbrasoft.OpenCode.Extensions.Data.EntityFrameworkCore;
using Pgvector;

#nullable disable

namespace OpenCode.Extensions.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(OpenCodeDbContext))]
    [Migration("20251203233049_AddMonologsAndModesTables")]
    partial class AddMonologsAndModesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.LegacyMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("InsertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("ParentMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParticipantIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TokensInput")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensOutput")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_LegacyMessages_MessageId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_LegacyMessages_SessionId");

                    b.ToTable("LegacyMessages", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.LegacyMonolog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("FirstMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsAborted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModeName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalPayload")
                        .HasColumnType("jsonb");

                    b.Property<string>("ParentMonologId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParticipantIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TokensInput")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensOutput")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LegacyMonologs_CreatedAt");

                    b.HasIndex("FirstMessageId")
                        .HasDatabaseName("IX_LegacyMonologs_FirstMessageId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_LegacyMonologs_SessionId");

                    b.ToTable("LegacyMonologs", (string)null);
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartsJson")
                        .HasColumnType("text");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.ModeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Modes_Name");

                    b.ToTable("Modes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "AI can modify files, run commands (full access)",
                            Name = "Build"
                        },
                        new
                        {
                            Id = 2,
                            Description = "AI only suggests and plans (read-only)",
                            Name = "Plan"
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Monolog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("FirstMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAborted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ModeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentMonologId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TokensInput")
                        .HasColumnType("integer");

                    b.Property<int?>("TokensOutput")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ModeId")
                        .HasDatabaseName("IX_Monologs_ModeId");

                    b.HasIndex("ParentMonologId")
                        .HasDatabaseName("IX_Monologs_ParentMonologId");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_Monologs_ParticipantId");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("IX_Monologs_ProviderId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_Monologs_SessionId");

                    b.HasIndex("SessionId", "Role")
                        .HasDatabaseName("IX_Monologs_Open")
                        .HasFilter("\"CompletedAt\" IS NULL");

                    b.ToTable("Monologs", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Assistant_Has_Parent", "\"Role\" = 1 OR \"ParentMonologId\" IS NOT NULL");

                            t.HasCheckConstraint("CHK_Closed_Has_LastMessageId", "\"CompletedAt\" IS NULL OR \"LastMessageId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Direct typing to terminal",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ContinuousListener - voice input",
                            Name = "VoiceAssistant"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Combination of keyboard and voice",
                            Name = "HumanCombination"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Direct Anthropic API",
                            Name = "Anthropic"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Direct OpenAI API",
                            Name = "OpenAI"
                        },
                        new
                        {
                            Id = 6,
                            Description = "GitHub Copilot",
                            Name = "GitHubCopilot"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Google AI Studio / Vertex AI",
                            Name = "GoogleAI"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Azure OpenAI Service",
                            Name = "AzureOpenAI"
                        });
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Message", b =>
                {
                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", "Participant")
                        .WithMany("Messages")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", "Provider")
                        .WithMany("Messages")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Provider");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Monolog", b =>
                {
                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.ModeEntity", "ModeEntity")
                        .WithMany("Monologs")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Monolog", "ParentMonolog")
                        .WithMany("ChildMonologs")
                        .HasForeignKey("ParentMonologId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", "Participant")
                        .WithMany("Monologs")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", "Provider")
                        .WithMany("Monologs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", "Session")
                        .WithMany("Monologs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeEntity");

                    b.Navigation("ParentMonolog");

                    b.Navigation("Participant");

                    b.Navigation("Provider");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.ModeEntity", b =>
                {
                    b.Navigation("Monologs");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Monolog", b =>
                {
                    b.Navigation("ChildMonologs");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Participant", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Monologs");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Provider", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Monologs");
                });

            modelBuilder.Entity("Olbrasoft.OpenCode.Extensions.Data.Entities.Session", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Monologs");
                });
#pragma warning restore 612, 618
        }
    }
}
