namespace Olbrasoft.OpenCode.Extensions.Data.Entities;

/// <summary>
/// AI model used for generating responses.
/// Examples: claude-sonnet-4, gpt-4-turbo, gemini-pro.
/// </summary>
public class Model
{
    /// <summary>
    /// Primary key (auto-increment).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Model identifier/name as used by provider.
    /// Example: "claude-sonnet-4-20250514", "gpt-4-turbo".
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Human-readable display name.
    /// Example: "Claude Sonnet 4", "GPT-4 Turbo".
    /// </summary>
    public string? DisplayName { get; set; }

    /// <summary>
    /// Provider that offers this model.
    /// </summary>
    public int? ProviderId { get; set; }

    /// <summary>
    /// Navigation property to Provider.
    /// </summary>
    public Provider? Provider { get; set; }

    /// <summary>
    /// Messages generated by this model.
    /// </summary>
    public ICollection<Message> Messages { get; set; } = [];
}
